name: floralbill
description: Floral shop billing app (Billing, Products, Reports, Settings) with Hive, web-ready.
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  intl: ^0.19.0
  file_picker: ^8.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  print_bluetooth_thermal: 1.1.6
  esc_pos_utils_plus: ^2.0.3
  image: ^4.1.7
  http: ^1.2.2
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/floralbill_icon.jpg"
  min_sdk_android: 21
  
  # Web configuration
  web:
    generate: true
    image_path: "assets/icon/floralbill_icon.jpg"
    background_color: "#4ade80"  # Green theme for floral shop
    theme_color: "#16a34a"       # Darker green
  
  # Windows configuration
  windows:
    generate: true
    image_path: "assets/icon/floralbill_icon.jpg"
    icon_size: 48
  
  # macOS configuration
  macos:
    generate: true
    image_path: "assets/icon/floralbill_icon.jpg"


flutter:
  uses-material-design: true

# Assets configuration
  assets:
  - assets/icon/